version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mori-pic-app
    volumes:
      - ./laravel:/var/www/html/laravel
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mori_pic
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - mori-pic-network

  web:
    image: nginx:latest
    container_name: mori-pic-web
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html/laravel
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mori-pic-network

  db:
    image: mysql:8.0
    container_name: mori-pic-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mori_pic
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mori-pic-network

  node:
    image: node:20
    container_name: mori-pic-node
    working_dir: /var/www/html/laravel
    volumes:
      - ./laravel:/var/www/html/laravel
    tty: true
    ports:
    - "5173:5173"
    networks:
      - mori-pic-network

volumes:
  dbdata:

networks:
  mori-pic-network:
    driver: bridge
